// ────────────────────────────────────────────────────────────────────────────
// DO NOT EDIT — This file is auto-generated by scripts/generate-defaults.mjs
// from gnd/schemas/canvas.yaml (single source of truth).
// ────────────────────────────────────────────────────────────────────────────

// Grid & theme
/** grid.size */
export const DEFAULT_GRID_SIZE = 10;
/** grid.snapEnabled */
export const DEFAULT_GRID_SNAP_ENABLED = true;
/** grid.showGrid */
export const DEFAULT_GRID_SHOW_GRID = true;
/** canvasTheme */
export const DEFAULT_CANVAS_THEME = "light";

// WTextGroup
/** style.opacity */
export const DEFAULT_WTG_OPACITY = 0.5;
/** style.backgroundColor */
export const DEFAULT_WTG_BACKGROUND_COLOR = "#000000";
/** style.width */
export const DEFAULT_WTG_WIDTH = 200;
/** style.borderRadius */
export const DEFAULT_WTG_BORDER_RADIUS = 8;
/** style.borderWidth */
export const DEFAULT_WTG_BORDER_WIDTH = 0;
/** style.shapeType */
export const DEFAULT_WTG_SHAPE_TYPE = "rounded-rectangle";

// WTextBlock
/** style.fontSize */
export const DEFAULT_WTB_FONT_SIZE = 24;
/** style.fontWeight */
export const DEFAULT_WTB_FONT_WEIGHT = "700";
/** style.color */
export const DEFAULT_WTB_COLOR = "#ffffff";
/** style.textAlign */
export const DEFAULT_WTB_TEXT_ALIGN = "center";
/** style.opacity */
export const DEFAULT_WTB_OPACITY = 1;
/** style.backgroundOpacity */
export const DEFAULT_WTB_BACKGROUND_OPACITY = 1;
